name: Full Extension Workflow

on:
  workflow_run:
    workflows: ["Pack Extension"]
    types:
      - completed
  workflow_dispatch:

jobs:
  # Step 1: Fetch Google Access Token
  fetchToken:
    runs-on: ubuntu-latest
    outputs:
      access_token_path: google-access-token
    steps:
      - id: fetchToken
        uses: cardinalby/google-api-fetch-token-action@v1
        with:
          clientId: ${{ secrets.G_CLIENT_ID }}
          clientSecret: ${{ secrets.G_CLIENT_SECRET }}
          refreshToken: ${{ secrets.G_REFRESH_TOKEN }}

      - name: Save access token
        run: echo "${{ steps.fetchToken.outputs.accessToken }}" > access_token.txt

      - name: Upload token as artifact
        uses: actions/upload-artifact@v3
        with:
          name: google-access-token
          path: access_token.txt

  # Step 2: Upload Extension
  uploadExtension:
    runs-on: ubuntu-latest
    needs: fetchToken
    steps:
      - name: Download token artifact
        uses: actions/download-artifact@v3
        with:
          name: google-access-token

      - name: Read access token
        id: read-token
        run: echo "ACCESS_TOKEN=$(cat access_token.txt)" >> $GITHUB_ENV

      - name: Upload to Chrome Web Store
        uses: cardinalby/webext-buildtools-chrome-webstore-action@v1
        with:
          zipFilePath: 'build/extension.zip'
          extensionId: 'ibnifmdhbaknbkgldmbnebeidephchno'
          apiAccessToken: ${{ env.ACCESS_TOKEN }}

  # Step 3: Publish Extension
  publishExtension:
    runs-on: ubuntu-latest
    needs: uploadExtension
    steps:
      - name: Download token artifact
        uses: actions/download-artifact@v3
        with:
          name: google-access-token

      - name: Read access token
        id: read-token
        run: echo "ACCESS_TOKEN=$(cat access_token.txt)" >> $GITHUB_ENV

      - name: Publish to Chrome Web Store
        uses: ardinalby/webext-buildtools-chrome-webstore-publish-action@v1
        with:
          extensionId: 'ibnifmdhbaknbkgldmbnebeidephchno'
          apiAccessToken: ${{ env.ACCESS_TOKEN }}
