name: Pack Extension

on:
  workflow_run:
    workflows: ["CodeQL"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Extension
      uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
      with:
        extensionDir: '.'
        zipFilePath: 'build/extension.zip'

    - name: Upload Extension Artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension-zip
        path: build/extension.zip
