name: Publish Extension

on:
  workflow_run:
    workflows: ["Publish Extension"]
    types:
      - completed
  workflow_dispatch:

jobs:
  publishExtension:
    runs-on: ubuntu-latest

    steps:
      - name: Download token artifact
        uses: actions/download-artifact@v3
        with:
          name: google-access-token

      - name: Read access token
        id: read-token
        run: echo "ACCESS_TOKEN=$(cat access_token.txt)" >> $GITHUB_ENV

      - name: Publish to Chrome Web Store
        uses: ardinalby/webext-buildtools-chrome-webstore-publish-action@v1
        with:
          extensionId: 'ibnifmdhbaknbkgldmbnebeidephchno'
          apiAccessToken: ${{ env.ACCESS_TOKEN }}
