name: Upload Extension

on:
  workflow_run:
    workflows: ["Fetch Google Access Token"]
    types:
      - completed
  workflow_dispatch:

jobs:
  uploadExtension:
    runs-on: ubuntu-latest

    steps:
      - name: Download token artifact
        uses: actions/download-artifact@v3
        with:
          name: google-access-token

      - name: Read access token
        id: read-token
        run: echo "ACCESS_TOKEN=$(cat access_token.txt)" >> $GITHUB_ENV

      - name: Upload to Chrome Web Store
        uses: cardinalby/webext-buildtools-chrome-webstore-action@v1
        with:
          zipFilePath: 'build/extension.zip'
          extensionId: 'ibnifmdhbaknbkgldmbnebeidephchno'
          apiAccessToken: ${{ env.ACCESS_TOKEN }}
